project:
  type: default

author: "Tewes Fröhling"
date: last-modified
date-format: MMMM D, YYYY
bibliography: reference_sg.bib
csl: apa.csl
link-citations: true

execute:
  echo: false
  warning: false
  eval: true
  cache: true

