---
title: |
  Data Exploration and Manipulation
subtitle: |
  Term paper social groups
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---


```{r}
#| label: setup

# To track computation time
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "haven",
  "sessioninfo",
  "brms",
  "bayesplot",
  "patchwork",
  "broom.mixed",
  "knitr",
  "ggpubr",
  "ggdag",
  "dagitty",
  "loo",
  "posterior",
  "modelsummary"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)

# Colours

col_1 <- "#FFAE42" # Orange Yellow
col_2 <- "#5D7860" # Dusky Green
col_3 <- "#BFABCC" # Grayish Lavender
col_4 <- "#D70040" # Carmine Red
chain_cols <- c(col_1, col_2, col_3, col_4)
```

# Loading Data

```{r}
#| label: data-import
# load dataset

raw_data <- read_delim(here("data", "01_raw", "Dataset_DeConinck_et_al.csv"), delim = ";")

```

```{r}
#| label: data-manipulation
# process the dataset by creating CARIN and RWA variables, and recoding variables to match the overall direction

processed_data <- raw_data |>
  mutate(
    V039_4r = 6 - V039_4,
    V039_5r = 6 - V039_5,
    CARIN_Attitude = rowMeans(pick(V039_1, V039_2)),
    CARIN_Control = rowMeans(pick(V039_3, V039_4r, V039_5r)),
    CARIN_Reciprocity = rowMeans(pick(V039_6, V039_7, V039_8)),
    CARIN_Identity = rowMeans(pick(V039_9, V039_10, V039_11)),
    CARIN_Need = rowMeans(pick(V039_12, V039_13)),
    CARIN_Total = rowMeans(pick(
      V039_1,
      V039_2,
      V039_3,
      V039_4r,
      V039_5r,
      V039_6,
      V039_7,
      V039_8,
      V039_9,
      V039_10,
      V039_11,
      V039_12,
      V039_12,
      V039_13
    )),
    V036_1r = 8 - V036_1,
    V036_4r = 8 - V036_4,
    V036_5r = 8 - V036_5,
    RWA_Submission = rowMeans(pick(V036_1r, V036_2)),
    RWA_Conventionalism = rowMeans(pick(V036_3, V036_4r)),
    RWA_Aggression = rowMeans(pick(V036_5r, V036_6)),
    RWA_Total = rowMeans(pick(
      V036_1r,
      V036_2,
      V036_3,
      V036_4r,
      V036_5r,
      V036_6
    )),
    V001 = as.factor(V001),
    Diploma2 = as.factor(Diploma2)
  )
```

```{r}
#| label: drop-cntry
# dropping Columbia and usa for European analysis and dropping the unused variables in the original dataset

clean_data <- processed_data |>
  filter(!cntry %in% c(8, 9)) |>
  select(
    V039_1,
    V039_2,
    V039_3,
    V039_4r,
    V039_5r,
    V039_6,
    V039_7,
    V039_8,
    V039_9,
    V039_10,
    V039_11,
    V039_12,
    V039_13,
    CARIN_Attitude,
    CARIN_Control,
    CARIN_Identity,
    CARIN_Need,
    CARIN_Reciprocity,
    CARIN_Total,
    V036_1r,
    V036_2,
    V036_3,
    V036_4r,
    V036_5r,
    V036_6,
    RWA_Aggression,
    RWA_Conventionalism,
    RWA_Submission,
    RWA_Total,
    V001,
    V002,
    Leeftijd3N,
    V010at,
    V010be,
    V010de,
    V010es,
    V010hu,
    V010it,
    V010se,
    Diploma2,
    V013,
    cntry,
    V037_1,
    V037_2,
    V037_3,
    V037_4,
    V037_5,
    V037_6,
    V037_7,
    V037_8
  )
```

# Export Dataset
```{r}
#| label: export-dataset
# exporting dataset to a processed csv file for easier and less cluttered workflow

write_csv2(
  clean_data,
  here("data", "02_processed", "processed_Dataset_DeConinck_et_al.csv")
)
```

# Data exploration

```{r}
#| label: fig-predictors
#| fig-cap: "distributions of the individual variables visualized"

deservingness_data <- read.csv2(
  "data/02_processed/processed_Dataset_DeConinck_et_al.csv"
)

# separate CARIN graphs

p1.1 <- ggplot(deservingness_data, aes(CARIN_Attitude)) +
  geom_bar(bins = 1, colour = "black", fill = col_1) +
  scale_x_continuous() +
  theme_minimal()

p1.2 <- ggplot(deservingness_data, aes(CARIN_Control)) +
  geom_bar(colour = "black", fill = col_2) +
  scale_x_continuous() +
  theme_minimal()

p1.3 <- ggplot(deservingness_data, aes(CARIN_Identity)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous() +
  theme_minimal()

p1.4 <- ggplot(deservingness_data, aes(CARIN_Need)) +
  geom_bar(colour = "black", fill = col_2) +
  scale_x_continuous() +
  theme_minimal()

p1.5 <- ggplot(deservingness_data, aes(CARIN_Reciprocity)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous() +
  theme_minimal()

p1.6 <- ggplot(deservingness_data, aes(CARIN_Total)) +
  geom_bar(colour = "black", fill = col_4) +
  scale_x_continuous() +
  theme_minimal()

# overall CARIN plot including CARIN_Total

CARIN_plot <- (p1.1 | p1.2 | p1.3) / (p1.4 | p1.5 | p1.6)

ggsave(
  filename = "figures/CARIN_distributions.png",
  plot = CARIN_plot,
  width = 8,
  height = 6,
  dpi = 300
)

# separate RWA graphs (2.x) including separate exploratory graphs for the variables out of which the RWA variables are coded (2.x.x)

p2.1 <- ggplot(deservingness_data, aes(RWA_Submission)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous() +
  theme_minimal()


p2.1.1 <- ggplot(deservingness_data, aes(V036_1r)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

p2.1.2 <- ggplot(deservingness_data, aes(V036_2)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

Submission_RWA_plot <- (p2.1.1 | p2.1.2 | p2.1)


p2.2 <- ggplot(deservingness_data, aes(RWA_Conventionalism)) +
  geom_bar(colour = "black", fill = col_2) +
  scale_x_continuous() +
  theme_minimal()

p2.2.1 <- ggplot(deservingness_data, aes(V036_3)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

p2.2.2 <- ggplot(deservingness_data, aes(V036_4r)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

Conventionalism_RWA_plot <- (p2.2.1 | p2.2.2 | p2.2)

p2.3 <- ggplot(deservingness_data, aes(RWA_Aggression)) +
  geom_bar(colour = "black", fill = col_3) +
  scale_x_continuous() +
  theme_minimal()

p2.3.1 <- ggplot(deservingness_data, aes(V036_5r)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

p2.3.2 <- ggplot(deservingness_data, aes(V036_6)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6, 7),
    label = c(
      "Strongly disagree",
      "2",
      "3",
      "Neither agree nor disagree",
      "5",
      "6",
      "Strongly agree"
    )
  ) +
  theme_minimal()

Aggression_RWA_plot <- (p2.3.1 | p2.3.2 | p2.3)

p2.4 <- ggplot(deservingness_data, aes(RWA_Total)) +
  geom_bar(colour = "black", fill = col_4) +
  scale_x_continuous() +
  theme_minimal()

RWA_Total_plot <- p2.4

ggsave(
  filename = "figures/RWA_Total_distribution.png",
  plot = RWA_Total_plot,
  width = 8,
  height = 6,
  dpi = 300
)

# create plot out of all three RWA subdimensions and RWA_Total to check

RWA_plot <- (p2.1 | p2.2) / (p2.3 | p2.4)

ggsave(
  filename = "figures/RWA_distributions.png",
  plot = RWA_plot,
  width = 8,
  height = 6,
  dpi = 300
)


# Create plot for appendix: CARIN criteria and RWA_Total

CARIN_RWA_plot <- (p1.1 | p1.2 | p1.3) / (p1.4 | p1.5 | p2.4)

ggsave(
  filename = "figures/CARIN_RWA_distributions.png",
  plot = CARIN_RWA_plot,
  width = 8,
  height = 5,
  dpi = 300
)

# exploratory graphs for the control variables

p3.1 <- ggplot(deservingness_data, aes(V001)) +
  geom_bar(colour = "black", fill = col_1) +
  scale_x_continuous(
    breaks = c(1, 2, 3),
    label = c("Male", "Female", "Other")
  ) +
  theme_minimal() +
  labs(
    x = "Sex (V001)"
  )

p3.2 <- ggplot(deservingness_data, aes(Leeftijd3N)) +
  geom_bar(colour = "black", fill = col_2) +
  scale_x_continuous(breaks = c(1, 2, 3), label = c("18-34", "35-54", "55+")) +
  labs(
    x = "label for x-axis",
    y = "label for y-axis"
  ) +
  theme_minimal() +
  labs(
    x = "Age group (Leeftijd3N)"
  )

p3.3 <- ggplot(deservingness_data, aes(V013)) +
  geom_bar(colour = "black", fill = col_3) +
  scale_x_continuous(
    breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    labels = c(
      "Far Left",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "Far Right"
    )
  ) +
  theme_minimal() +
  labs(x = "political orientation (V013)")

p3.4 <- ggplot(deservingness_data, aes(Diploma2)) +
  geom_bar(colour = "black", fill = col_4) +
  scale_x_continuous(
    breaks = c(0, 1, 2),
    labels = c("", "no tertiary degree", "tertiary degree")
  ) +
  theme_minimal() +
  labs(x = "Teritary Degree")

# Create plot for appendix with all control variables

Control_plot <- (p3.1 | p3.2) / (p3.3 | p3.4)

ggsave(
  filename = "figures/Control_distributions.png",
  plot = Control_plot,
  width = 8,
  height = 4.5,
  dpi = 300
)
```

# Session Info

```{r}
#| label: session-info

session_info()
```


# Computation Time

```{r}
#| label: computation-time

end_time <- Sys.time()

computation_time <- end_time - start_time

message(paste(
  "Computation completed in:",
  round(as.numeric(computation_time, units = "secs"), 2),
  "seconds.
"
))
```


  
